### ISSUE TITLE
Bug when using url

### ISSUE THREAD

**Issue by JohnConnor123** [imanuella/Ts-to-MP4-Converter#2]
Unfortunately, the option via URL does not work:(
![image](https://github.com/imanuella/Ts-to-MP4-Converter/assets/106041597/114848d9-3924-49fa-8a8a-2e24085f69bb)

**Comment by JohnConnor123** [comment]
I would also like to attach the link with which problems arise, but I’m afraid that your fix will only work for my particular case.

**Comment by imanuella** [comment]
I'm sorry it took so long to reply. can you share the link you are talking about? I have tried the code using my usual test link and it works fine in my case.
![image](https://github.com/imanuella/Ts-to-MP4-Converter/assets/56574374/7ee2b5b3-b254-4491-b718-5045a36660f7)
![win](https://github.com/imanuella/Ts-to-MP4-Converter/assets/56574374/4a523e12-1468-4c6c-9ecf-d66b6f78de2e)

**Comment by JohnConnor123** [comment]
Sure
https://my.mts-link.ru/82053743/2031424288/record-new/1746092686

**Comment by imanuella** [comment]
i'm sorry, I think the problem is that you pasted the wrong kind of link. please use the direct link for the video url. the link should have .ts at the end. keep in mind that longer videos and larger files will take a very long time to convert.
in your case, i suggest to use a download manager like idm to download the video first. after that try using the code to convert it.

**Comment by JohnConnor123** [comment]
That is, as far as I understand, it is impossible to parse all .ts files using a .m3u8 file from any site?

**Comment by imanuella** [comment]
I found a way to download the .ts file from your [link](https://events-delivery-records.webinar.ru/streamer/default/storage/events-storage.webinar.ru/api-storage/files/wowza/2024/04/15/11d6fae30de51b3ce792804f9afb7ef6a43822fbecc87806f94da49daab.mp4/chunklist.m3u8) using this [script](https://pastebin.com/vmVhYJHT). I've tried it and the script downloads .ts files from the m3u8 playlist and then converts them to mp4.

![image](https://github.com/imanuella/Ts-to-MP4-Converter/assets/56574374/62a83923-c34c-4a13-9da1-da35f7f6fc33)
![image](https://github.com/imanuella/Ts-to-MP4-Converter/assets/56574374/744fb41a-c924-4462-9e3a-a39c1f386255)
